### ISSUE TITLE
Image position and dimensions

### ISSUE THREAD

**Issue by IIITM-Jay** [IIITM-Jay/Property-management-System-Django-Full-Stack-#11]
**Describe the bug**
The image is not at the center of the page and also not clearly visible due to the missing dimension(Height/ width) specifications.

**To Reproduce**
1. Go to 'DBMS module'
2. Click on 'flow_sequence_diag.md'
3. Find the image tag.
4. See the error

**Expected behavior**
The image should display to the center of the page with clear visibility.

**To-do list**
- [ ] Correct the position of the image so that it can display at the center.
- [ ] Dimensions need to be correctly specified
- [ ] If possible, a good outline/ border would be greatful

**Comment by 96RadhikaJadhav** [comment]
@IIITM-Jay  Could you please assign this issue to me? I wish to work on it.

**Comment by IIITM-Jay** [comment]
@96RadhikaJadhav if you wish wish you can go through this issue..:tada:

**Comment by 96RadhikaJadhav** [comment]
> Hi, @96RadhikaJadhav!
> Welcome to The Property Management System!!! 🏡
> 
> Can you please introduce a little bit about yourself as from which college you are, branch and year... or anything you wish... ✨ 🎉 ... so that it will help me know about the contributing members and can even mention them
> How do you come to know about this repo... 👍

Hello, @IIITM-Jay! 
I'm currently doing a job. I'm 2017 passed out from MIT College, Aurangabad, Maharashtra.

**Comment by 96RadhikaJadhav** [comment]
@IIITM-Jay I have created a PR. Could you please review it and let me know if any other changes required.

**Comment by IIITM-Jay** [comment]
@96RadhikaJadhav Radhika I reopening this again if you want to add something , you can do so... congratulations once agian to be a part of this community. :1st_place_medal:
