### ISSUE TITLE
Users Prespective : The front view documentation

### ISSUE THREAD

**Issue by IIITM-Jay** [IIITM-Jay/Property-management-System-Django-Full-Stack-#12]
**Describe the issue**
* This issue is relevant to the documentation part of the project/ management system.
* This same documentation can be viewed from the project report ***download project report*** badge on the README.md page.
* The aim is to design the same page in the markdown format so that it can give the clear picture of the whole front-end view of this management system.
* It will provide the clear understanding of the various functionalities  of the operations offered to the user.
* It will help to elaborate the whole system in short text with a clear venn diagram

**To Reproduce**
1. Click on the ![](https://img.shields.io/badge/download-project%20report-success) in the README.md file , i.e. on the landing page of the code. (page no. 22)
2. Navigate to the ***4.3.3*** Section named **Users Prespective : The front view**
3. Go through it and understand it carefully
4. Note down various specification like: 
    * Which words to be bold
    * The orientation of the letters and words
    * Image position
    * Bullet points and its exact types
    * Image caption

**Expected behavior**
The expected outcome will be the exact replica of the section mentioned in the project report in the markdown format only so that it can be made importable. 

**Screenshots**
![Screenshot from 2021-01-02 17-29-34](https://user-images.githubusercontent.com/65283880/103457214-1e270580-4d23-11eb-9701-4f3139af8991.png)

**To-do list**
We have to reproduce the same page  as above in markdown format. This can be fabricated to the following parts/ portions that can be completed sequentially:
- [ ] The heading with correct orientation
- [ ] The image with correct position and dimension
- [ ] The caption
- [ ] The bullet points
- [ ] The text with correct size

**Desktop (please complete the following information):**
 - OS: Ubuntu/ Windows
 - Browser Mozilla firefox/ Chrome

**Additional context**
If any relevant information that needs to be added is highly appreciable.

**Comment by smriti1313** [comment]
Hi, i wuld like to work on this but under DWoC label. Is there a chance of me getting this issue? Thank you

**Comment by IIITM-Jay** [comment]
@smriti1313 yeah sure ... You can go ahead.. but first of all may I know a little bit of yours so as to know of my contributing members and can even mention them in some other projects

Welcome to the Property Management System 🏡

**Comment by smriti1313** [comment]
@IIITM-Jay Hello, I am a pre final year CSE student. I have learned Django,SQLite and currently practicing Javascript. 
Thank you

**Comment by Amit366** [comment]
@IIITM-Jay is this issue open.
