### ISSUE TITLE
Enhancement in the login page

### ISSUE THREAD

**Issue by IIITM-Jay** [IIITM-Jay/Property-management-System-Django-Full-Stack-#13]
**Describe the issue**
This issue can be taken as an enhancement to the system. The present login page, which is being provided in the screenshot of the description of this issue, is looking not so efficient and effective with so much extent . 
* *The idea is  to make the login page attractive enough to be deployed so that more real world users find it easy to use and in a very friendly manner*

**To Reproduce**
1. Go to ***/front-end*** directory.
2. Go  through the following files and understand the coding carefully:
    * base.html
    * login.html
    * logout.html
3. See the enhancement opportunities in the above files.
4. Have different outlines coordinated with various css stylings in-hand prior to get into your hands into the code given.
5. Code it! 

**Expected behavior**
An attractive and effective login page to be deployed.

## Screenshots

***The curent pages of the login/ logout page looks as follows:***

![Screenshot from 2021-01-02 18-54-12](https://user-images.githubusercontent.com/65283880/103458608-d22e8d80-4d2f-11eb-891a-81360ce02891.png)
![Screenshot from 2021-01-02 19-15-11](https://user-images.githubusercontent.com/65283880/103458612-d9559b80-4d2f-11eb-9b0c-34d4fdaa804a.png)

**To-do list**
- [ ] A clear and concise outline of how you are going to design the page.
- [ ] The login page
- [ ] Subsequent logout page
- [ ] The flow must be maintained between login and logout
- [ ] Moderate to good level of css stylesheets 
- [ ] the supported HTML5 version tags 
- [ ] Javascript can be used to have better enhancement look
- [ ] Screenshot of the pages created before doing the PR so that we can discuss as to have more improvements required at the present moment
- [ ] Can be done in three phases so that loads can be reduced
    *  - [ ] base/ behind screen of the login page
    *  - [ ] login page itself
    *  - [ ] susequent logout page

**Comment by kenkirito** [comment]
can i work on this issue and please add dwoc tags

**Comment by IIITM-Jay** [comment]
@kenkirito  may I know little bit of yours, like in which college you are studying, which year and branch... 🤗 So that I should know about my contributing members

**Comment by IIITM-Jay** [comment]
And then you can proceed further ...

**Comment by kenkirito** [comment]
myself lakshya Mishra currently a  professional in data science working with consulting firm. exploring web development in my free time

**Comment by IIITM-Jay** [comment]
@kenkirito I have assigned this issue to you and now can do the pr... : 🚀

**Comment by kenkirito** [comment]
okay

**Comment by kenkirito** [comment]
how to run this give some instructions. i can't find anything in readme?

**Comment by kenkirito** [comment]
https://user-images.githubusercontent.com/68530218/105644525-0115ca80-5ebc-11eb-9283-5ef928b0a632.mp4

**Comment by kenkirito** [comment]
not able to run the project but try a HTML and css page

**Comment by kenkirito** [comment]
@IIITM-Jay

**Comment by IIITM-Jay** [comment]
@kenkirito lakshya you can edit the message after you comment, I think you must have missed out this feature.. anyways..
Coming on to your actual query I must say that you first of all visit the GitHub page already present at this repo and then try to think how to modify it more and how can we attract more real world users.
This must include your first phase of outline of how you are thinking to redesign, secondly the languages you are going to use in effective manner and thirdly the final screenshot of the page you have designed.

**Comment by kenkirito** [comment]
![mishra](https://user-images.githubusercontent.com/68530218/105709977-7cb75c00-5f3c-11eb-82e9-9437715faf9b.png)

**Comment by kenkirito** [comment]
@IIITM-Jay created using html and css

**Comment by kenkirito** [comment]
![error](https://user-images.githubusercontent.com/68530218/105832386-e6437300-5fed-11eb-9d08-a1aa61598028.png)

**Comment by kenkirito** [comment]
@IIITM-Jay review

**Comment by IIITM-Jay** [comment]
@kenkirito lakshya I have edited the comment on your first screenshot...

**Comment by IIITM-Jay** [comment]
Lakshya you haven't copied the code for the web page you have designed right? Because if so this will come under plagiarism and this is an online repo... We should not done this kind of thing that's why confirming from you

**Comment by kenkirito** [comment]
yes

**Comment by kenkirito** [comment]
![png](https://user-images.githubusercontent.com/68530218/106017848-f12dfe80-60e6-11eb-89db-2024c406b297.png)
