### ISSUE TITLE
Image Description in DBMS Module

### ISSUE THREAD

**Issue by IIITM-Jay** [IIITM-Jay/Property-management-System-Django-Full-Stack-#22]
**Describe the bug**
Image caption is needed to be added to all the figures present int DBMS Module with the headers so as to get a clear and concise description of what the image is depicting.

**To Reproduce**
1. Go to DBMS Module
2. Click on all the files one by one.
3. Read the files and understand them carefully of what the project is all about.
4. See The description above and work on it.

**Expected behavior**
The caption must be added to just below the figures.

**To-do list**
you can go through or open up this issue into multiple PR's for separate DBMS module into the following categories:

- [ ] System Requirement Analysis
- [ ] Flow Sequence Diagram
- [ ] UML classes and modules

**Comment by AnshMishra2001** [comment]
Can I work on this?

**Comment by IIITM-Jay** [comment]
@AnshMishra2001 Welcome to the Property management System :house_with_garden: 
may I know little bit of yours, like in which college you are studying, which year and branch... hugs So that I should know about my contributing members.... and then start working on it

**Comment by AnshMishra2001** [comment]
Sure, I am a second year student. at Manipal University , studying Information Technology.
